In [55]:
from sklearn import set_config
set_config(transform_output="pandas")

In [56]:
import pandas as pd
import numpy as np

In [57]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.pipeline import Pipeline, make_pipeline

In [58]:
df = pd.read_csv('Titanic_Dataset.csv')

In [59]:
df.head(4)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [60]:
df.drop(columns=['PassengerId', 'Name',  'Ticket','Cabin'], inplace = True)

In [61]:
df.head(4)

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S

In [62]:
type(df)

pandas.core.frame.DataFrame

In [63]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['Survived']), df['Survived'], test_size=0.2, random_state=42)

In [64]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((712, 7), (179, 7), (712,), (179,))

In [65]:
type(X_train), type(X_test), y_train.dtype, y_test.dtype

(pandas.core.frame.DataFrame,
 pandas.core.frame.DataFrame,
 dtype('int64'),
 dtype('int64'))

In [66]:
X_train.head(4)

     Pclass   Sex   Age  SibSp  Parch     Fare Embarked
331       1  male  45.5      0      0  28.5000        S
733       2  male  23.0      0      0  13.0000        S
382       3  male  32.0      0      0   7.9250        S
704       3  male  26.0      1      0   7.8542        S

In [67]:
X_train.isnull().sum()

Pclass        0
Sex           0
Age         140
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [68]:
y_train

331    0
733    0
382    0
704    0
813    0
      ..
106    1
270    0
860    0
435    1
102    0
Name: Survived, Length: 712, dtype: int64

In [69]:
y_train.dtype, type(X_train )

(dtype('int64'), pandas.core.frame.DataFrame)

In [70]:
transformer1 = ColumnTransformer([
    ('impute_age', SimpleImputer(), [2]),
    ('impute_embarked', SimpleImputer(strategy="most_frequent"), [6] )
    ], remainder='passthrough'
)

In [71]:
transformer1

ColumnTransformer(remainder='passthrough',
                  transformers=[('impute_age', SimpleImputer(), [2]),
                                ('impute_embarked',
                                 SimpleImputer(strategy='most_frequent'),
                                 [6])])

In [72]:
step1 = transformer1.fit_transform(X_train)
print(type(step1))

<class 'pandas.core.frame.DataFrame'>

In [73]:
step1.columns

Index(['impute_age__Age', 'impute_embarked__Embarked', 'remainder__Pclass',
       'remainder__Sex', 'remainder__SibSp', 'remainder__Parch',
       'remainder__Fare'],
      dtype='object')

In [74]:
step1

,impute_age__Age,impute_embarked__Embarked,remainder__Pclass,remainder__Sex,remainder__SibSp,remainder__Parch,remainder__Fare
331,45.500000,S,1,male,0,0,28.5000
733,23.000000,S,2,male,0,0,13.0000
382,32.000000,S,3,male,0,0,7.9250
704,26.000000,S,3,male,1,0,7.8542
813,6.000000,S,3,female,4,2,31.2750
...,...,...,...,...,...,...,...
106,21.000000,S,3,female,0,0,7.6500
270,29.498846,S,1,male,0,0,31.0000
860,41.000000,S,3,male,2,0,14.1083
435,14.000000,S,1,female,1,2,120.0000
102,21.000000,S,1,male,0,1,77.2875

In [75]:
transformer2 = ColumnTransformer(
[
 ('ohe', OneHotEncoder(sparse_output=False, handle_unknown='ignore'),
  [1,3])
],
remainder='passthrough'
)

In [76]:
step2 = transformer2.fit_transform(X_train)
print(type(step2))

<class 'pandas.core.frame.DataFrame'>

In [77]:
step2.columns

Index(['ohe__Sex_female', 'ohe__Sex_male', 'ohe__SibSp_0', 'ohe__SibSp_1',
       'ohe__SibSp_2', 'ohe__SibSp_3', 'ohe__SibSp_4', 'ohe__SibSp_5',
       'ohe__SibSp_8', 'remainder__Pclass', 'remainder__Age',
       'remainder__Parch', 'remainder__Fare', 'remainder__Embarked'],
      dtype='object')

In [78]:
transformer1

ColumnTransformer(remainder='passthrough',
                  transformers=[('impute_age', SimpleImputer(), [2]),
                                ('impute_embarked',
                                 SimpleImputer(strategy='most_frequent'),
                                 [6])])

In [79]:
transformer2

ColumnTransformer(remainder='passthrough',
                  transformers=[('ohe',
                                 OneHotEncoder(handle_unknown='ignore',
                                               sparse_output=False),
                                 [1, 3])])

In [80]:
# step2 = transformer2.fit_transform(step1)
# print(step2[:5])

In [81]:
step2.columns

Index(['ohe__Sex_female', 'ohe__Sex_male', 'ohe__SibSp_0', 'ohe__SibSp_1',
       'ohe__SibSp_2', 'ohe__SibSp_3', 'ohe__SibSp_4', 'ohe__SibSp_5',
       'ohe__SibSp_8', 'remainder__Pclass', 'remainder__Age',
       'remainder__Parch', 'remainder__Fare', 'remainder__Embarked'],
      dtype='object')

In [82]:
transformer3 = ColumnTransformer(
    [
        ('scale', MinMaxScaler(),slice(0,10) )
    ], remainder = 'passthrough'
)

In [83]:
transformer3

ColumnTransformer(remainder='passthrough',
                  transformers=[('scale', MinMaxScaler(), slice(0, 10, None))])

In [84]:
transformer4 = SelectKBest(score_func=chi2, k =8)

In [85]:
transformer4

SelectKBest(k=8, score_func=<function chi2 at 0x7769bdcd8400>)

In [112]:
transformer5 = DecisionTreeClassifier()

In [113]:
transformer5

DecisionTreeClassifier()

In [114]:
X_train.shape, y_train.shape

((712, 7), (712,))

<h1> Use Pipelines </h1>

<p> difference between pipeline and make_pipeline is that we need to pass every single step in pipeline and in make_pipeline () we just pass the names directly

In [115]:
pipe = make_pipeline(transformer1, transformer2, transformer3, transformer4, transformer5)

In [116]:
pipe

Pipeline(steps=[('columntransformer-1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('impute_age', SimpleImputer(),
                                                  [2]),
                                                 ('impute_embarked',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6])])),
                ('columntransformer-2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 3])])),
                ('columntransformer-3',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 10, None))])),
                ('selectkbest',
                 SelectKBest(k=8,
                             score_func=<function chi2 at 0x7769bdcd8400>)),
                ('decisiontreeclassifier', DecisionTreeClassifier())])

In [117]:
print(X_train.columns)

Index(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'], dtype='object')

In [118]:
X_train

     Pclass     Sex   Age  SibSp  Parch      Fare Embarked
331       1    male  45.5      0      0   28.5000        S
733       2    male  23.0      0      0   13.0000        S
382       3    male  32.0      0      0    7.9250        S
704       3    male  26.0      1      0    7.8542        S
813       3  female   6.0      4      2   31.2750        S
..      ...     ...   ...    ...    ...       ...      ...
106       3  female  21.0      0      0    7.6500        S
270       1    male   NaN      0      0   31.0000        S
860       3    male  41.0      2      0   14.1083        S
435       1  female  14.0      1      2  120.0000        S
102       1    male  21.0      0      1   77.2875        S

[712 rows x 7 columns]

In [119]:
y_train

331    0
733    0
382    0
704    0
813    0
      ..
106    1
270    0
860    0
435    1
102    0
Name: Survived, Length: 712, dtype: int64

In [120]:
# Y = pd.DataFrame(y_train)

In [121]:
# type(X_train)

In [122]:
# type(Y)

In [123]:
# print(step1[:5])

In [124]:
# print(X_train.columns)

In [125]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('columntransformer-1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('impute_age', SimpleImputer(),
                                                  [2]),
                                                 ('impute_embarked',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6])])),
                ('columntransformer-2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 3])])),
                ('columntransformer-3',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 10, None))])),
                ('selectkbest',
                 SelectKBest(k=8,
                             score_func=<function chi2 at 0x7769bdcd8400>)),
                ('decisiontreeclassifier', DecisionTreeClassifier())])

<h3> More about pipelines </h3>

In [126]:
pipe.named_steps

{'columntransformer-1': ColumnTransformer(remainder='passthrough',
                   transformers=[('impute_age', SimpleImputer(), [2]),
                                 ('impute_embarked',
                                  SimpleImputer(strategy='most_frequent'),
                                  [6])]),
 'columntransformer-2': ColumnTransformer(remainder='passthrough',
                   transformers=[('ohe',
                                  OneHotEncoder(handle_unknown='ignore',
                                                sparse_output=False),
                                  [1, 3])]),
 'columntransformer-3': ColumnTransformer(remainder='passthrough',
                   transformers=[('scale', MinMaxScaler(), slice(0, 10, None))]),
 'selectkbest': SelectKBest(k=8, score_func=<function chi2 at 0x7769bdcd8400>),
 'decisiontreeclassifier': DecisionTreeClassifier()}

In [129]:
pipe.named_steps['columntransformer-1']

ColumnTransformer(remainder='passthrough',
                  transformers=[('impute_age', SimpleImputer(), [2]),
                                ('impute_embarked',
                                 SimpleImputer(strategy='most_frequent'),
                                 [6])])

In [101]:
from sklearn import set_config
set_config(display='diagram')

In [102]:
y_pred = pipe.predict(X_test)

In [103]:
y_pred

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1])

In [104]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)

In [105]:
accuracy

0.7877094972067039

In [106]:
from sklearn.model_selection import cross_val_score
cross_validation = cross_val_score(pipe, X_train, y_train, cv=5, scoring='accuracy').mean()

In [107]:
cross_validation

np.float64(0.7810400866738896)

<h3>GridSearch </h3>

In [130]:
params = {
    'decisiontreeclassifier__max_depth' : [1,2,3,4,5, None]
}

In [131]:
pipe.get_params().keys()

dict_keys(['memory', 'steps', 'transform_input', 'verbose', 'columntransformer-1', 'columntransformer-2', 'columntransformer-3', 'selectkbest', 'decisiontreeclassifier', 'columntransformer-1__force_int_remainder_cols', 'columntransformer-1__n_jobs', 'columntransformer-1__remainder', 'columntransformer-1__sparse_threshold', 'columntransformer-1__transformer_weights', 'columntransformer-1__transformers', 'columntransformer-1__verbose', 'columntransformer-1__verbose_feature_names_out', 'columntransformer-1__impute_age', 'columntransformer-1__impute_embarked', 'columntransformer-1__impute_age__add_indicator', 'columntransformer-1__impute_age__copy', 'columntransformer-1__impute_age__fill_value', 'columntransformer-1__impute_age__keep_empty_features', 'columntransformer-1__impute_age__missing_values', 'columntransformer-1__impute_age__strategy', 'columntransformer-1__impute_embarked__add_indicator', 'columntransformer-1__impute_embarked__copy', 'columntransformer-1__impute_embarked__fill_value', 'columntransformer-1__impute_embarked__keep_empty_features', 'columntransformer-1__impute_embarked__missing_values', 'columntransformer-1__impute_embarked__strategy', 'columntransformer-2__force_int_remainder_cols', 'columntransformer-2__n_jobs', 'columntransformer-2__remainder', 'columntransformer-2__sparse_threshold', 'columntransformer-2__transformer_weights', 'columntransformer-2__transformers', 'columntransformer-2__verbose', 'columntransformer-2__verbose_feature_names_out', 'columntransformer-2__ohe', 'columntransformer-2__ohe__categories', 'columntransformer-2__ohe__drop', 'columntransformer-2__ohe__dtype', 'columntransformer-2__ohe__feature_name_combiner', 'columntransformer-2__ohe__handle_unknown', 'columntransformer-2__ohe__max_categories', 'columntransformer-2__ohe__min_frequency', 'columntransformer-2__ohe__sparse_output', 'columntransformer-3__force_int_remainder_cols', 'columntransformer-3__n_jobs', 'columntransformer-3__remainder', 'columntransformer-3__sparse_threshold', 'columntransformer-3__transformer_weights', 'columntransformer-3__transformers', 'columntransformer-3__verbose', 'columntransformer-3__verbose_feature_names_out', 'columntransformer-3__scale', 'columntransformer-3__scale__clip', 'columntransformer-3__scale__copy', 'columntransformer-3__scale__feature_range', 'selectkbest__k', 'selectkbest__score_func', 'decisiontreeclassifier__ccp_alpha', 'decisiontreeclassifier__class_weight', 'decisiontreeclassifier__criterion', 'decisiontreeclassifier__max_depth', 'decisiontreeclassifier__max_features', 'decisiontreeclassifier__max_leaf_nodes', 'decisiontreeclassifier__min_impurity_decrease', 'decisiontreeclassifier__min_samples_leaf', 'decisiontreeclassifier__min_samples_split', 'decisiontreeclassifier__min_weight_fraction_leaf', 'decisiontreeclassifier__monotonic_cst', 'decisiontreeclassifier__random_state', 'decisiontreeclassifier__splitter'])

In [132]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(pipe, params, cv=5, scoring= 'accuracy' )
grid.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('columntransformer-1',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('impute_age',
                                                                         SimpleImputer(),
                                                                         [2]),
                                                                        ('impute_embarked',
                                                                         SimpleImputer(strategy='most_frequent'),
                                                                         [6])])),
                                       ('columntransformer-2',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('ohe',
                                                                         OneHotEncoder(handle_unknown='ignore',
                                                                                       s...),
                                                                         [1,
                                                                          3])])),
                                       ('columntransformer-3',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('scale',
                                                                         MinMaxScaler(),
                                                                         slice(0, 10, None))])),
                                       ('selectkbest',
                                        SelectKBest(k=8,
                                                    score_func=<function chi2 at 0x7769bdcd8400>)),
                                       ('decisiontreeclassifier',
                                        DecisionTreeClassifier())]),
             param_grid={'decisiontreeclassifier__max_depth': [1, 2, 3, 4, 5,
                                                               None]},
             scoring='accuracy')

In [133]:
grid.best_score_

np.float64(0.8033093666896484)

In [134]:
grid.best_params_

{'decisiontreeclassifier__max_depth': 3}

<h1> To Export the pipeline

In [136]:
import pickle

In [139]:
pickle.dump(pipe, open('models/pipe.pkl', 'wb'))