In [288]:
from sklearn import set_config
set_config(transform_output="pandas")

In [289]:
import pandas as pd
import numpy as np

In [290]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.pipeline import Pipeline, make_pipeline

In [291]:
df = pd.read_csv('Titanic_Dataset.csv')

In [292]:
df.head(4)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [293]:
df.drop(columns=['PassengerId', 'Name',  'Ticket','Cabin'], inplace = True)

In [294]:
df.head(4)

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S

In [295]:
type(df)

pandas.core.frame.DataFrame

In [296]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['Survived']), df['Survived'], test_size=0.2, random_state=42)

In [297]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((712, 7), (179, 7), (712,), (179,))

In [298]:
type(X_train), type(X_test), y_train.dtype, y_test.dtype

(pandas.core.frame.DataFrame,
 pandas.core.frame.DataFrame,
 dtype('int64'),
 dtype('int64'))

In [299]:
X_train.head(4)

     Pclass   Sex   Age  SibSp  Parch     Fare Embarked
331       1  male  45.5      0      0  28.5000        S
733       2  male  23.0      0      0  13.0000        S
382       3  male  32.0      0      0   7.9250        S
704       3  male  26.0      1      0   7.8542        S

In [300]:
X_train.isnull().sum()

Pclass        0
Sex           0
Age         140
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [301]:
y_train

331    0
733    0
382    0
704    0
813    0
      ..
106    1
270    0
860    0
435    1
102    0
Name: Survived, Length: 712, dtype: int64

In [302]:
y_train.dtype, type(X_train )

(dtype('int64'), pandas.core.frame.DataFrame)

In [303]:
transformer1 = ColumnTransformer([
    ('impute_age', SimpleImputer(), [2]),
    ('impute_embarked', SimpleImputer(strategy="most_frequent"), [6] )
    ], remainder='passthrough'
)

In [304]:
step1 = transformer1.fit_transform(X_train)
print(type(step1))

<class 'pandas.core.frame.DataFrame'>

In [305]:
transformer2 = ColumnTransformer(
[
 ('ohe', OneHotEncoder(sparse_output=False, handle_unknown='ignore'),
  [2,7])
],
remainder='passthrough'
)

In [307]:
# step2 = transformer2.fit_transform(X_train)
# print(type(step2))

In [ ]:
transformer1

ColumnTransformer(remainder='passthrough',
                  transformers=[('impute_age', SimpleImputer(), [2]),
                                ('impute_embarked',
                                 SimpleImputer(strategy='most_frequent'),
                                 [6])])

In [ ]:
transformer2

ColumnTransformer(remainder='passthrough',
                  transformers=[('ohe',
                                 OneHotEncoder(handle_unknown='ignore',
                                               sparse_output=False),
                                 [1, 6])])

In [308]:
step2 = transformer2.fit_transform(step1)
print(step2[:5])

ValueError: all features must be in [0, 6] or [-7, 0]

In [ ]:
step2.columns

Index(['ohe__impute_embarked__Embarked_C', 'ohe__impute_embarked__Embarked_Q',
       'ohe__impute_embarked__Embarked_S', 'ohe__remainder__Fare_0.0',
       'ohe__remainder__Fare_4.0125', 'ohe__remainder__Fare_5.0',
       'ohe__remainder__Fare_6.2375', 'ohe__remainder__Fare_6.4375',
       'ohe__remainder__Fare_6.45', 'ohe__remainder__Fare_6.4958',
       ...
       'ohe__remainder__Fare_227.525', 'ohe__remainder__Fare_247.5208',
       'ohe__remainder__Fare_262.375', 'ohe__remainder__Fare_263.0',
       'ohe__remainder__Fare_512.3292', 'remainder__impute_age__Age',
       'remainder__remainder__Pclass', 'remainder__remainder__Sex',
       'remainder__remainder__SibSp', 'remainder__remainder__Parch'],
      dtype='object', length=228)

In [ ]:
transformer3 = ColumnTransformer(
    [
        ('scale', MinMaxScaler(),slice(0,10) )
    ], remainder = 'passthrough'
)

In [ ]:
transformer3

ColumnTransformer(remainder='passthrough',
                  transformers=[('scale', MinMaxScaler(), slice(0, 10, None))])

In [ ]:
transformer4 = SelectKBest(score_func=chi2, k =8)

In [ ]:
transformer4

SelectKBest(k=8, score_func=<function chi2 at 0x7984b8280400>)

In [ ]:
transformer5 = DecisionTreeClassifier()

In [ ]:
transformer5

DecisionTreeClassifier()

In [ ]:
X_train.shape, y_train.shape

((712, 7), (712,))

<h1> Use Pipelines </h1>

<p> difference between pipeline and make_pipeline is that we need to pass every single step in pipeline and in make_pipeline () we just pass the names directly

In [ ]:
pipe = make_pipeline(transformer1, transformer2, transformer3, transformer4, transformer5)

In [ ]:
pipe

Pipeline(steps=[('columntransformer-1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('impute_age', SimpleImputer(),
                                                  [2]),
                                                 ('impute_embarked',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6])])),
                ('columntransformer-2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 6])])),
                ('columntransformer-3',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 10, None))])),
                ('selectkbest',
                 SelectKBest(k=8,
                             score_func=<function chi2 at 0x7984b8280400>)),
                ('decisiontreeclassifier', DecisionTreeClassifier())])

In [ ]:
print(X_train.columns)

Index(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'], dtype='object')

In [ ]:
X_train

     Pclass     Sex   Age  SibSp  Parch      Fare Embarked
331       1    male  45.5      0      0   28.5000        S
733       2    male  23.0      0      0   13.0000        S
382       3    male  32.0      0      0    7.9250        S
704       3    male  26.0      1      0    7.8542        S
813       3  female   6.0      4      2   31.2750        S
..      ...     ...   ...    ...    ...       ...      ...
106       3  female  21.0      0      0    7.6500        S
270       1    male   NaN      0      0   31.0000        S
860       3    male  41.0      2      0   14.1083        S
435       1  female  14.0      1      2  120.0000        S
102       1    male  21.0      0      1   77.2875        S

[712 rows x 7 columns]

In [ ]:
y_train

331    0
733    0
382    0
704    0
813    0
      ..
106    1
270    0
860    0
435    1
102    0
Name: Survived, Length: 712, dtype: int64

In [ ]:
Y = pd.DataFrame(y_train)

In [ ]:
type(X_train)

pandas.core.frame.DataFrame

In [ ]:
type(Y)

pandas.core.frame.DataFrame

In [ ]:
print(step1[:5])

     impute_age__Age impute_embarked__Embarked  remainder__Pclass  \
331             45.5                         S                  1
733             23.0                         S                  2
382             32.0                         S                  3
704             26.0                         S                  3
813              6.0                         S                  3

    remainder__Sex  remainder__SibSp  remainder__Parch  remainder__Fare
331           male                 0                 0          28.5000
733           male                 0                 0          13.0000
382           male                 0                 0           7.9250
704           male                 1                 0           7.8542
813         female                 4                 2          31.2750

In [ ]:
print(X_train.columns)

Index(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'], dtype='object')

In [ ]:
pipe.fit(X_train, y_train)

ValueError: could not convert string to float: 'male'