In [1]:
import pandas as pd
import numpy as np

<h3> Working with dates

In [22]:
orders = pd.read_csv('orders.csv')
orders.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [23]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [24]:
orders['date'] = pd.to_datetime(orders['date'] )

In [25]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [26]:
orders['date_year']= orders['date'].dt.year

In [27]:
orders.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

In [28]:
orders['month']= orders['date'].dt.month

In [29]:
orders.head()

        date  product_id  city_id  orders  date_year  month
0 2019-12-10        5628       25       3       2019     12
1 2018-08-15        3646       14     157       2018      8
2 2018-10-23        1859       25       1       2018     10
3 2019-08-17        7292       25       1       2019      8
4 2019-01-06        4344       25       3       2019      1

In [30]:
orders['day']= orders['date'].dt.day

In [31]:
orders.head()

        date  product_id  city_id  orders  date_year  month  day
0 2019-12-10        5628       25       3       2019     12   10
1 2018-08-15        3646       14     157       2018      8   15
2 2018-10-23        1859       25       1       2018     10   23
3 2019-08-17        7292       25       1       2019      8   17
4 2019-01-06        4344       25       3       2019      1    6

In [32]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
 4   date_year   1000 non-null   int32
 5   month       1000 non-null   int32
 6   day         1000 non-null   int32
dtypes: datetime64[ns](1), int32(3), int64(3)
memory usage: 43.1 KB

In [33]:
orders['day_name']= orders['date'].dt.day_name()
orders.head(4)

        date  product_id  city_id  orders  date_year  month  day   day_name
0 2019-12-10        5628       25       3       2019     12   10    Tuesday
1 2018-08-15        3646       14     157       2018      8   15  Wednesday
2 2018-10-23        1859       25       1       2018     10   23    Tuesday
3 2019-08-17        7292       25       1       2019      8   17   Saturday

In [34]:
orders['month_name'] = orders['date'].dt.month_name()
orders.head(4)

,date,product_id,city_id,orders,date_year,month,day,day_name,month_name
0,2019-12-10,5628,25,3,2019,12,10,Tuesday,December
1,2018-08-15,3646,14,157,2018,8,15,Wednesday,August
2,2018-10-23,1859,25,1,2018,10,23,Tuesday,October
3,2019-08-17,7292,25,1,2019,8,17,Saturday,August

In [ ]:
# whether it is weekend or not