In [70]:
import pandas as pd
import numpy as np

<h3> Working with dates

In [71]:
orders = pd.read_csv('orders.csv')
orders.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [72]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [73]:
orders['date'] = pd.to_datetime(orders['date'] )

In [74]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [75]:
orders['date_year']= orders['date'].dt.year

In [76]:
orders.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

In [77]:
orders['month']= orders['date'].dt.month

In [78]:
orders.head()

        date  product_id  city_id  orders  date_year  month
0 2019-12-10        5628       25       3       2019     12
1 2018-08-15        3646       14     157       2018      8
2 2018-10-23        1859       25       1       2018     10
3 2019-08-17        7292       25       1       2019      8
4 2019-01-06        4344       25       3       2019      1

In [79]:
orders['day']= orders['date'].dt.day

In [80]:
orders.head()

        date  product_id  city_id  orders  date_year  month  day
0 2019-12-10        5628       25       3       2019     12   10
1 2018-08-15        3646       14     157       2018      8   15
2 2018-10-23        1859       25       1       2018     10   23
3 2019-08-17        7292       25       1       2019      8   17
4 2019-01-06        4344       25       3       2019      1    6

In [81]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
 4   date_year   1000 non-null   int32
 5   month       1000 non-null   int32
 6   day         1000 non-null   int32
dtypes: datetime64[ns](1), int32(3), int64(3)
memory usage: 43.1 KB

In [82]:
orders['day_name']= orders['date'].dt.day_name()
orders.head(4)

        date  product_id  city_id  orders  date_year  month  day   day_name
0 2019-12-10        5628       25       3       2019     12   10    Tuesday
1 2018-08-15        3646       14     157       2018      8   15  Wednesday
2 2018-10-23        1859       25       1       2018     10   23    Tuesday
3 2019-08-17        7292       25       1       2019      8   17   Saturday

In [83]:
orders['month_name'] = orders['date'].dt.month_name()
orders.head(4)

,date,product_id,city_id,orders,date_year,month,day,day_name,month_name
0,2019-12-10,5628,25,3,2019,12,10,Tuesday,December
1,2018-08-15,3646,14,157,2018,8,15,Wednesday,August
2,2018-10-23,1859,25,1,2018,10,23,Tuesday,October
3,2019-08-17,7292,25,1,2019,8,17,Saturday,August

In [84]:
# whether it is weekend or not

orders['is_weekend'] = np.where(orders['day_name'].isin(['Saturday','Sunday']), 1,0)
orders.head(4)

,date,product_id,city_id,orders,date_year,month,day,day_name,month_name,is_weekend
0,2019-12-10,5628,25,3,2019,12,10,Tuesday,December,0
1,2018-08-15,3646,14,157,2018,8,15,Wednesday,August,0
2,2018-10-23,1859,25,1,2018,10,23,Tuesday,October,0
3,2019-08-17,7292,25,1,2019,8,17,Saturday,August,1

In [85]:
# extracting the number of the quarter based on the date

orders['quarter'] = orders['date'].dt.quarter
orders.head()

,date,product_id,city_id,orders,date_year,month,day,day_name,month_name,is_weekend,quarter
0,2019-12-10,5628,25,3,2019,12,10,Tuesday,December,0,4
1,2018-08-15,3646,14,157,2018,8,15,Wednesday,August,0,3
2,2018-10-23,1859,25,1,2018,10,23,Tuesday,October,0,4
3,2019-08-17,7292,25,1,2019,8,17,Saturday,August,1,3
4,2019-01-06,4344,25,3,2019,1,6,Sunday,January,1,1

In [86]:
# to divide the quarter into semesters
orders['semester'] = np.where(orders['quarter'].isin([1,2]),1,2)

orders.head()

,date,product_id,city_id,orders,date_year,month,day,day_name,month_name,is_weekend,quarter,semester
0,2019-12-10,5628,25,3,2019,12,10,Tuesday,December,0,4,2
1,2018-08-15,3646,14,157,2018,8,15,Wednesday,August,0,3,2
2,2018-10-23,1859,25,1,2018,10,23,Tuesday,October,0,4,2
3,2019-08-17,7292,25,1,2019,8,17,Saturday,August,1,3,2
4,2019-01-06,4344,25,3,2019,1,6,Sunday,January,1,1,1

In [87]:
# extract collapsed date
import datetime

today = datetime.datetime.today()
today

datetime.datetime(2026, 4, 1, 21, 52, 11, 717377)

In [88]:
(today-orders['date']).dt.days.head(4)

0    2304
1    2786
2    2717
3    2419
Name: date, dtype: int64

In [90]:
np.round((today -orders['date']) / np.timedelta64(1, 'W'),0)

0      329.0
1      398.0
2      388.0
3      346.0
4      378.0
       ...
995    390.0
996    382.0
997    360.0
998    370.0
999    337.0
Name: date, Length: 1000, dtype: float64

In [91]:
messages =pd.read_csv('messages.csv')

In [92]:
messages.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [93]:
messages['date']= pd.to_datetime(messages['date'])

In [94]:
messages.head(4)

                 date                                                msg
0 2013-12-15 00:50:00                           ищу на сегодня мужика 37
1 2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2 2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3 2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...

In [101]:
messages.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [109]:
messages['hour']=messages['date'].dt.hour
messages['minute']=messages['date'].dt.minute
messages['second']=messages['date'].dt.second

In [110]:
messages['time'] = messages['date'].dt.time

In [111]:
messages['day'] = today-messages['date']

In [112]:
messages.head()

,date,msg,hour,minute,second,day,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,4490 days 21:02:11.717377,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,4354 days 22:12:11.717377,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,4840 days 21:31:11.717377,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,4142 days 21:21:11.717377,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,4539 days 22:41:11.717377,23:11:00

In [113]:
(today - messages['date'])/np.timedelta64(1,'s')

0      3.880117e+08
1      3.762655e+08
2      4.182535e+08
3      3.579457e+08
4      3.922513e+08
           ...
995    4.432213e+08
996    3.845615e+08
997    4.247361e+08
998    4.347587e+08
999    3.718600e+08
Name: date, Length: 1000, dtype: float64

In [114]:
(today - messages['date'])/np.timedelta64(1,'m')

0      6.466862e+06
1      6.271092e+06
2      6.970891e+06
3      5.965761e+06
4      6.537521e+06
           ...
995    7.387022e+06
996    6.409358e+06
997    7.078935e+06
998    7.245978e+06
999    6.197667e+06
Name: date, Length: 1000, dtype: float64

In [115]:
(today - messages['date'])/np.timedelta64(1,'h')

0      107781.036588
1      104518.203255
2      116181.519921
3       99429.353255
4      108958.686588
           ...
995    123117.036588
996    106822.636588
997    117982.253255
998    120766.303255
999    103294.453255
Name: date, Length: 1000, dtype: float64