In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from sklearn.model_selection import train_test_split
# from sklearn.linear_model import LinearRegression
# from sklearn.metrics import r2_score 
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score

from sklearn.compose import ColumnTransformer

In [19]:
df = pd.read_csv('/home/varsha/PracticePython/100DaysOfMl/ML6_Pipelines/Titanic_Dataset.csv')

In [20]:
df.head(4)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [24]:
df_new = df.drop(columns =['PassengerId', 'Name', 'Ticket', 'Cabin', 'Sex', 'Embarked', 'Pclass'], axis=1)

In [25]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Age       714 non-null    float64
 2   SibSp     891 non-null    int64
 3   Parch     891 non-null    int64
 4   Fare      891 non-null    float64
dtypes: float64(2), int64(3)
memory usage: 34.9 KB

In [26]:
df_new

     Survived   Age  SibSp  Parch     Fare
0           0  22.0      1      0   7.2500
1           1  38.0      1      0  71.2833
2           1  26.0      0      0   7.9250
3           1  35.0      1      0  53.1000
4           0  35.0      0      0   8.0500
..        ...   ...    ...    ...      ...
886         0  27.0      0      0  13.0000
887         1  19.0      0      0  30.0000
888         0   NaN      1      2  23.4500
889         1  26.0      0      0  30.0000
890         0  32.0      0      0   7.7500

[891 rows x 5 columns]

In [27]:
df_new.isna().sum()

Survived      0
Age         177
SibSp         0
Parch         0
Fare          0
dtype: int64

In [28]:
df_new['Age'].fillna(df_new['Age'].mean(), inplace=True)

/tmp/ipykernel_5884/3227039731.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_new['Age'].fillna(df_new['Age'].mean(), inplace=True)

In [29]:
df_new['family'] = df_new['SibSp'] + df_new['Parch']

In [30]:
df_new

     Survived        Age  SibSp  Parch     Fare  family
0           0  22.000000      1      0   7.2500       1
1           1  38.000000      1      0  71.2833       1
2           1  26.000000      0      0   7.9250       0
3           1  35.000000      1      0  53.1000       1
4           0  35.000000      0      0   8.0500       0
..        ...        ...    ...    ...      ...     ...
886         0  27.000000      0      0  13.0000       0
887         1  19.000000      0      0  30.0000       0
888         0  29.699118      1      2  23.4500       3
889         1  26.000000      0      0  30.0000       0
890         0  32.000000      0      0   7.7500       0

[891 rows x 6 columns]

In [31]:
df_new.drop(columns=['Parch', 'SibSp'], inplace=True)

In [51]:
X_train, X_test, Y_train, Y_test = train_test_split(df_new.drop('Survived', axis=1), df_new['Survived'], test_size=0.2, random_state=42)

In [52]:
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((712, 3), (179, 3), (712,), (179,))

In [53]:
X_train

           Age      Fare  family
331  45.500000   28.5000       0
733  23.000000   13.0000       0
382  32.000000    7.9250       0
704  26.000000    7.8542       1
813   6.000000   31.2750       6
..         ...       ...     ...
106  21.000000    7.6500       0
270  29.699118   31.0000       0
860  41.000000   14.1083       2
435  14.000000  120.0000       3
102  21.000000   77.2875       1

[712 rows x 3 columns]

<h3> Without Binarizer

In [54]:
classifier1 = DecisionTreeClassifier()
classifier1.fit(X_train, Y_train)
Y_pred = classifier1.predict(X_test)
accuracy_score(Y_test, Y_pred)

0.6871508379888268

In [55]:
X_train

           Age      Fare  family
331  45.500000   28.5000       0
733  23.000000   13.0000       0
382  32.000000    7.9250       0
704  26.000000    7.8542       1
813   6.000000   31.2750       6
..         ...       ...     ...
106  21.000000    7.6500       0
270  29.699118   31.0000       0
860  41.000000   14.1083       2
435  14.000000  120.0000       3
102  21.000000   77.2875       1

[712 rows x 3 columns]

In [67]:
from sklearn.preprocessing import Binarizer

transformer = ColumnTransformer(transformers=[('bin', Binarizer(copy=False), ['family'])], remainder='passthrough')

X_train_tansf = transformer.fit_transform(X_train)

X_test_transf = transformer.transform(X_test)

In [68]:
# converting into dataframe
df_trf= pd.DataFrame(X_train_tansf, columns=['family', 'Age', 'Fare'])
df_trf

     family        Age      Fare
0       0.0  45.500000   28.5000
1       0.0  23.000000   13.0000
2       0.0  32.000000    7.9250
3       1.0  26.000000    7.8542
4       1.0   6.000000   31.2750
..      ...        ...       ...
707     0.0  21.000000    7.6500
708     0.0  29.699118   31.0000
709     1.0  41.000000   14.1083
710     1.0  14.000000  120.0000
711     1.0  21.000000   77.2875

[712 rows x 3 columns]

In [71]:
df_trf['family'].tail(10)

702    0.0
703    0.0
704    0.0
705    1.0
706    1.0
707    0.0
708    0.0
709    1.0
710    1.0
711    1.0
Name: family, dtype: float64

<h3> After Binarizer

In [70]:
clf = DecisionTreeClassifier()
clf.fit(X_train_tansf, Y_train)
Y_pred = clf.predict(X_test_transf )
print(accuracy_score( Y_test, Y_pred))

0.6759776536312849